#!/bin/sh
n=$1
shift

export PARALLEL=yes
export vcpus=2
export net_admin=192.168.$((50+$n*2))
export net_public=192.168.$((51+$n*2))
export adminnetmask=255.255.254.0

# Note: Please set the storage options for deploying SUSE Cloud.

# LVM Configuration variables.
# If you want to re-use existing LVM Volume Group:
export cloudvg=mkcloud # This will use an existing LVM Volume Group and not destroy other volumes.
# If you are using dedicated disk/PV/file disk, then setup cloudpv variable.
# This will use an LVM Physical Volume exclusively and destroy all the volumes under this PV. Use this for dedicated setup or file disk.
#export cloudpv=/dev/loop1  # Uncomment and replace loopX with the required number Ex: loop0 or the LVM partition incase of physical disk.

export virtualcloud=c$n
export cloud=$virtualcloud
